export { default as DialogRoot } from './DialogRoot.vue'
export { default as DialogTrigger } from './DialogTrigger.vue'
export { default as DialogContent,type DialogContentProps } from './DialogContent.vue'
export { default as DialogPortal } from './DialogPortal.vue'
export { default as DialogTitle } from './DialogTitle.vue'
export { default as DialogClose } from './DialogClose.vue'
export { default as DialogOverlay,type DialogOverlayProps } from './DialogOverlay.vue'
export { default as DialogDescription } from './DialogDescription.vue'
